name: Frontend CI

on:
  push:
  pull_request:
    branches: [main]

defaults: &node_setup
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Setup Node.js v20
    uses: actions/setup-node@v4
    with:
      node-version: "20.x"
      cache: "npm"

jobs:
  tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - <<: *node_setup
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test -- --run --config vitest.config.ts

  build:
    runs-on: ubuntu-latest
    needs: tests_and_lint
    steps:
      - <<: *node_setup
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
