name: Frontend CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test -- --run --config vitest.config.ts

  build:
    runs-on: ubuntu-latest
    needs: tests_and_lint
    steps:
      - uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build
