# .github/workflows/tests.yml
name: Tests CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Run linter
      #   run: npm run lint

      - name: Run tests
        run: npm run test -- --run

      - name: Run build
        run: npm run build
